DEBUG := n
TARGET := host_spi2_flash_hw
OBJS := ast_host_spi2_flash.o 

EXTRA_CFLAGS += -I${SPXINC}/global
EXTRA_CFLAGS += -I${SPXINC}/helper
EXTRA_CFLAGS += -I${SPXINC}/host_spi2_flash

-include ${TOOLDIR}/rules/Rules.make.drivers
